### ISSUE TITLE
Mixed line endings make for a not-so-useful "git status"

### ISSUE THREAD

**Issue by colbyrussell** [sufficiently-secure/document-viewer#83]
I decided to start messing with some Android stuff; doing all this on a spare machine running Ubuntu 14.04 LTS.

When I clone the repo and immediately cd into the directory and run "git status", it comes pre-loaded with unstaged changes:

> colby@sepiatu:~/src/third-party/document-viewer$ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   art/drawables/sources/External Sources/Antarctica_on_the_globe_(red).svg
> 	modified:   art/drawables/sources/External Sources/Blank_globe.svg
> 	modified:   art/drawables/sources/External Sources/File Antarctica_on_the_globe_(red).svg.htm
> 	modified:   art/drawables/sources/External Sources/File Blank_globe.svg.htm
> 	modified:   art/drawables/sources/External Sources/File Question_book.svg.htm
> 	modified:   art/drawables/sources/External Sources/File Stop_hand_nuvola_black.svg.htm
> 	modified:   art/drawables/sources/External Sources/File Stop_hand_nuvola_black.svg_files/analytics_prod.js
> 	modified:   art/drawables/sources/External Sources/Question_book.svg
> 	modified:   art/drawables/sources/External Sources/Stop_hand_nuvola_black.svg
> 	modified:   art/drawables/sources/Original/Guidelines.txt
> 	modified:   art/drawables/sources/readme.txt
> 	modified:   document-viewer/src/main/java/org/afzkl/colorpicker/ColorPickerDialog.java
> 	modified:   document-viewer/src/main/java/org/afzkl/colorpicker/views/ColorPanelView.java
> 	modified:   document-viewer/src/main/java/org/afzkl/colorpicker/views/ColorPickerView.java
> 	modified:   document-viewer/src/main/res/layout/opdsitem.xml

This seems to be due mixed usage of CRLF and LF line endings; there are some Windows-style CRLF line endings in the handful of files listed above.  We should [drop the carriage returns in these files and standardize on Unix-style line endings for the project](https://help.github.com/articles/dealing-with-line-endings/), otherwise "git status" is quite noisy and not terribly useful.

**Comment by colbyrussell** [comment]
.... there's actually something else going on here, because it turns out there're a lot more files with Windows-style line endings besides those listed above.  Not sure if I should cancel the pull request or not.

**Comment by dschuermann** [comment]
I would propose fixing the endings for all files and adding a gitattributes for the future

**Comment by dschuermann** [comment]
Hmm, I just saw, there is already a gitattributes file. So not sure whats going on here.

**Comment by tuxor1337** [comment]
I also noticed that and so far ignored it, because it never applied to files I was working on. However, only files which have been originally included from external sources seem to be affected by this problem. And at this point a much more general problem of this repository comes into play: The repository contains thousands of files that are included from third party sources. And in my opinion, this i bad practice. Repositories should rather include third party sources as submodules or pull in the required source code separately via package managers etc. in some init script (that's the reason why I added the `init.sh` script).

**Comment by tuxor1337** [comment]
Oh, and yes, there is a gitattributes file, but it has been added at a late state of this project. At that state, all those "corrupt" files already existed and haven't been touched by anyone since.

**Comment by tuxor1337** [comment]
By the way, isn't it rediculous how much artwork is used by this app? The UI is so simple and it could (should!) be even simpler, I don't know why we need so much overhead in terms of art work...

**Comment by dschuermann** [comment]
:grin: I don't know. All artwork (except the icon) is untouched since I forked it from EBookdroid.

**Comment by tuxor1337** [comment]
Yes, I know. It was already in a horrible state when the original developer decided to turn ebookdroid into a non-free app. I suppose, at some point he decided to take the huge effort of cleaning up the code and the UI. But while he was doing so, he noticed that he was basically rewriting 80 percent of the code. And at such a point, it's of course comprehensible to expect some reward for one's efforts...

**Comment by dschuermann** [comment]
@tuxor1337 I moved the repo over to a new org: sufficiently-secure. To separate some apps from my personal github. I added you to the Devs group with write access.

**Comment by colbyrussell** [comment]
Sorry about my previous comment.  After some rest I looked into it this morning and those files are in fact the only ones with Windows-style line endings.  You can confirm:

> colby@ruta-corsica$ grep --exclude-dir=.git -lIre "^M" ./
> ./art/drawables/sources/Original/Guidelines.txt
> ./art/drawables/sources/readme.txt
> ./art/drawables/sources/External Sources/File Blank_globe.svg.htm
> ./art/drawables/sources/External Sources/File Antarctica_on_the_globe_(red).svg.htm
> ./art/drawables/sources/External Sources/Antarctica_on_the_globe_(red).svg
> ./art/drawables/sources/External Sources/File Question_book.svg.htm
> ./art/drawables/sources/External Sources/Stop_hand_nuvola_black.svg
> ./art/drawables/sources/External Sources/File Stop_hand_nuvola_black.svg.htm
> ./art/drawables/sources/External Sources/Question_book.svg
> ./art/drawables/sources/External Sources/File Stop_hand_nuvola_black.svg_files/analytics_prod.js
> ./art/drawables/sources/External Sources/Blank_globe.svg
> ./document-viewer/src/main/java/org/afzkl/colorpicker/views/ColorPickerView.java
> ./document-viewer/src/main/java/org/afzkl/colorpicker/views/ColorPanelView.java
> ./document-viewer/src/main/java/org/afzkl/colorpicker/ColorPickerDialog.java
> ./document-viewer/src/main/res/layout/opdsitem.xml

(...where "^M" is not typed with a literal "^" and "M"—which would, of course, match lines beginning with a capital M—but instead entered by typing Ctrl+V followed by Ctrl+M to enter a literal CR character.)

You can confirm that it fixes the issue:
> colby@ruta-corsica$ git clone https://github.com/colbyrussell/document-viewer ./d-v
> Cloning into './d-v'...
> remote: Counting objects: 22772, done.
> remote: Compressing objects: 100% (31/31), done.
> remote: Total 22772 (delta 2), reused 0 (delta 0), pack-reused 22739
> Receiving objects: 100% (22772/22772), 40.51 MiB | 4.12 MiB/s, done.
> Resolving deltas: 100% (16243/16243), done.
> Checking connectivity... done.
> colby@ruta-corsica$ cd ./d-v
> colby@ruta-corsica$ grep --exclude-dir=.git -lIre "^M" ./
> colby@ruta-corsica$ git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> nothing to commit, working directory clean

**Comment by colbyrussell** [comment]
> By the way, isn't it rediculous how much artwork is used by this app? The UI is so simple and it could (should!) be even simpler, I don't know why we need so much overhead in terms of art work... However, as I mentioned in another issue: Document Viewer's UI needs a huge cleanup. Not only from the user's point of view, but also from the coder's point of view, it's such a mess!

Those are the types of things I set out to do when I immediately ran into this last night.  But not being able to do "git commit -a" or having an effective "git status" puts a damper on potential contributions.

**Comment by tuxor1337** [comment]
@dschuermann Okay, I'm not so much into this github permission management, but it seems like I'm now a member (collaborator) of sufficiently-secure but still don't have write access to this repository.

@colbyrussell Your pull request is absolutely fine. I will merge it as soon as I have the necessary write permissions.

**Comment by tuxor1337** [comment]
Speaking about an effective `git status`: I also suggest adding `ignore = dirty` to the `.gitmodules` file in order to remove notifications about changes in the mupdf submodule.

**Comment by dschuermann** [comment]
@tuxor1337 Sry, you have now write permissions

**Comment by tuxor1337** [comment]
@dschuermann Thanks :)
